spring:
  application:
    name: log-analyzer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.182.235:3306/log_analyzer?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password:
    tomcat:
      max-active: 20
      max-idle: 10
      min-idle: 5
      default-auto-commit: false
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000

  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        strategy: com.cn.zktd.saber.log.analyzer.utils.MPSNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache.use_second_level_cache: true
        cache.use_query_cache: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  output:
    ansi:
      enabled: DETECT

logging:
  level:
    root: info
    org.hibernate: INFO
    com.cn.zktd.saber.log.analyzer: info
  path: logs/
  file: ${spring.application.name}.log

